#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
mkdir $OPENSHIFT_DATA_DIR/teamsysdata{,-backup}
cd $OPENSHIFT_REPO_DIR/webapps
D=ROOT.war
rm ${D}
V=4.2
F=youtrack-${V}.war
wget http://download.jetbrains.com/charisma/archive/${F}
mv ${F} ${D}
jar xvf ${D}
sed -ig 's,${user.home}/teamsysdata-backup,'${OPENSHIFT_DATA_DIR}/teamsysdata-backup, WEB-INF/web.xml
sed -ig 's,${user.home}/teamsysdata,'${OPENSHIFT_DATA_DIR}/teamsysdata, WEB-INF/web.xml
jar cvf ${D} .
rm -rf META-INF WEB-INF
